### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/python-snarks#1]
## Abstract
- list of  error occured
```
(.venv) % python groth16/groth_setup.py
Traceback (most recent call last):
  File "groth_setup.py", line 4, in <module>
    from ..arithmetic import bn128_Field, bn128_FieldPolynomial, log2, mul_scalar, G1, G2, pairing, FQ, field_properties
```
```
(.venv) % python groth16/groth_setup.py
Traceback (most recent call last):
  File "groth16/groth_setup.py", line 4, in <module>
    from ..arithmetic import bn128_Field, bn128_FieldPolynomial, log2, mul_scalar, G1, G2, pairing, FQ, field_properties
ImportError: attempted relative import with no known parent package
```
```
(.venv) % python -m groth16/groth_setup.py
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/kevin/dev/python-snarks/groth16/groth_setup.py", line 4, in <module>
    from ..arithmetic import bn128_Field, bn128_FieldPolynomial, log2, mul_scalar, G1, G2, pairing, FQ, field_properties
ImportError: attempted relative import with no known parent package
```

```
(.venv) % python -m python-snark.groth16.groth_setup
/Users/kevin/dev/python-snarks/.venv/bin/python: Error while finding module specification for 'python-snark.groth16.groth_setup' (ModuleNotFoundError: No module named 'python-snark')
```

## Environment Setup(command history)
```
$ git clone https://github.com/Onther-Tech/python-snarks.git
$ cd python-snarks
$ virtualenv .venv
$ . .venv/bin/activate
(.venv) $ pip install cached_property
(.venv) $ pip install wasmer==1.0.0a3
(.venv) $ pip install wasmer_compiler_cranelift==1.0.0a3

```

**Comment by modagi** [comment]
python-snarks works as a package. so for now, you should run this package on the parent directory of python-snarks.

anyway I will add test code. then you will be able to test it comfortably.
